"use client";

import { useState, useRef, useEffect, useCallback } from "react";
import { RefreshCw, Wand2, Lightbulb, AlertCircle, Pin, Code, Eye } from "lucide-react";
import { useUIStream, type Spec } from "@json-render/react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { DashboardRenderer } from "@/lib/render/renderer";
import { useSpecData, extractCollections } from "@/hooks/use-spec-data";
import { useSettings } from "@/hooks/use-settings";
import { useCollections } from "@/hooks/use-collections";
import { useWidgetHub } from "@/hooks/use-widget-hub";

// Rotating prompts the AI picks from to create varied dashboards each time
const WORKSHOP_PROMPTS = [
  "Create a comprehensive executive dashboard that shows the most interesting patterns across all my data. Include key metrics, trends over time, and category breakdowns.",
  "Build a dashboard focused on recent activity and trends. Show what's changed recently, highlight outliers, and surface any interesting correlations between collections.",
  "Design an analytical dashboard that tells a story about my data. Start with the big picture, then drill into the most interesting details. Use creative chart combinations.",
  "Create a dashboard that compares and contrasts data across my collections. Find connections, show distributions, and highlight the most noteworthy data points.",
  "Build a visual summary of everything in my data. Focus on making it beautiful and insightful — use stat cards for key numbers, charts for trends, and tables for recent items.",
];

export function WorkshopPanel() {
  const { settings } = useSettings();
  const { collections } = useCollections();
  const { startFlyAnimation } = useWidgetHub();
  const [generatedSpec, setGeneratedSpec] = useState<Spec | null>(null);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [showJson, setShowJson] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);
  const specContainerRef = useRef<HTMLDivElement>(null);

  const { spec, isStreaming, error, send, clear } = useUIStream({
    api: "/api/generate",
    onError: (err) => console.error("Workshop generation error:", err),
  });

  const { data, setData, dataVersion, isLoading, refresh, handleDataChange } = useSpecData(
    generatedSpec,
  );

  // When streaming completes, save the final spec
  const prevStreamingRef = useRef(isStreaming);
  useEffect(() => {
    if (prevStreamingRef.current && !isStreaming && spec) {
      setGeneratedSpec(spec);
      clear();
    }
    prevStreamingRef.current = isStreaming;
  }, [isStreaming, spec, clear]);

  const generate = useCallback(async () => {
    setGeneratedSpec(null);

    const prompt = WORKSHOP_PROMPTS[Math.floor(Math.random() * WORKSHOP_PROMPTS.length)]!;

    const context: Record<string, unknown> = {
      mode: "workshop",
      apiKey: settings.openrouter_api_key,
      model: settings.openrouter_model,
    };

    if (collections.length > 0) {
      context.collections = collections.map((c) => ({
        name: c.name,
        description: c.description,
        fields: c.fields,
      }));
    }

    await send(prompt, context);
  }, [send, settings.openrouter_api_key, settings.openrouter_model, collections]);

  // Auto-generate on first visit when we have collections + API key
  useEffect(() => {
    if (
      !hasAutoGenerated &&
      !isStreaming &&
      collections.length > 0 &&
      settings.openrouter_api_key
    ) {
      setHasAutoGenerated(true);
      generate();
    }
  }, [hasAutoGenerated, isStreaming, collections.length, settings.openrouter_api_key, generate]);

  const handleAddToHub = useCallback(() => {
    if (!generatedSpec || !specContainerRef.current) return;
    const rect = specContainerRef.current.getBoundingClientRect();
    const specCollections = extractCollections(generatedSpec);
    startFlyAnimation(rect, { title: "Workshop Dashboard", spec: generatedSpec, collections: specCollections });
  }, [generatedSpec, startFlyAnimation]);

  const hasApiKey = !!settings.openrouter_api_key;
  const hasCollections = collections.length > 0;
  const activeSpec = isStreaming ? spec : generatedSpec;
  const canGenerate = hasApiKey && hasCollections && !isStreaming;

  // Not ready state — missing API key or collections
  if (!hasApiKey || !hasCollections) {
    return (
      <div className="flex flex-col h-full bg-dot-grid">
        <div className="flex-1 flex items-center justify-center">
          <div className="flex flex-col items-center gap-4 max-w-sm text-center px-4">
            <div className="size-12 rounded-2xl bg-muted/50 flex items-center justify-center">
              <AlertCircle className="size-5 text-muted-foreground" />
            </div>
            <div className="flex flex-col gap-1.5">
              <h2 className="text-sm font-medium text-foreground">Not ready yet</h2>
              <p className="text-sm text-muted-foreground">
                {!hasApiKey
                  ? "Set your OpenRouter API key in Settings to get started."
                  : "Connect to SurrealDB and add some collections first."}
              </p>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full bg-dot-grid">
      {/* Header bar */}
      <div className="px-4 py-3 flex items-center justify-between border-b border-border/30">
        <div className="flex items-center gap-2.5">
          <Lightbulb className="size-3.5 text-primary" />
          <span className="text-xs font-medium text-muted-foreground">
            AI-generated views of your data
          </span>
        </div>
        <div className="flex items-center gap-2">
          {collections.length > 0 && (
            <div className="flex gap-1 mr-1">
              {collections.slice(0, 4).map((c) => (
                <Badge key={c.name} variant="secondary" className="text-[10px] px-1.5 py-0">
                  {c.name}
                </Badge>
              ))}
              {collections.length > 4 && (
                <Badge variant="secondary" className="text-[10px] px-1.5 py-0">
                  +{collections.length - 4}
                </Badge>
              )}
            </div>
          )}
          <Button
            variant="outline"
            size="sm"
            className="h-7 text-xs gap-1.5 rounded-lg"
            onClick={generate}
            disabled={!canGenerate}
          >
            <RefreshCw className={`size-3 ${isStreaming ? "animate-spin" : ""}`} />
            {isStreaming ? "Generating..." : "New ideas"}
          </Button>
        </div>
      </div>

      {/* Content */}
      <ScrollArea className="flex-1" ref={scrollRef}>
        <div className="max-w-3xl mx-auto px-4 py-6">
          {/* Loading state */}
          {isStreaming && !activeSpec && (
            <div className="flex flex-col items-center justify-center py-20 gap-6">
              <div className="size-16 rounded-2xl bg-primary/10 flex items-center justify-center animate-pulse-glow">
                <Wand2 className="size-6 text-primary" />
              </div>
              <div className="flex flex-col items-center gap-2">
                <p className="text-lg font-medium text-foreground">Crafting your dashboard</p>
                <p className="text-sm text-muted-foreground">Analyzing collections and finding insights</p>
              </div>
              <div className="w-full max-w-sm space-y-3 mt-2">
                <div className="h-2 rounded-full animate-shimmer" />
                <div className="h-2 rounded-full animate-shimmer" style={{ animationDelay: "0.3s" }} />
                <div className="h-2 rounded-full animate-shimmer w-2/3" style={{ animationDelay: "0.6s" }} />
              </div>
            </div>
          )}

          {/* Rendered dashboard */}
          {activeSpec && (
            <div ref={specContainerRef} className="border border-border/50 rounded-xl p-4 bg-card/80 backdrop-blur-sm animate-fade-in-up">
              <div className="flex justify-end gap-1 mb-3">
                <Button
                  variant="ghost"
                  size="icon"
                  className="size-7 rounded-lg text-muted-foreground hover:text-primary"
                  onClick={handleAddToHub}
                  title="Pin to Widget Hub"
                  disabled={isStreaming}
                >
                  <Pin className="size-3.5" />
                </Button>
                <Button
                  variant="ghost"
                  size="icon"
                  className="size-7 rounded-lg text-muted-foreground hover:text-foreground"
                  onClick={() => setShowJson((v) => !v)}
                  title={showJson ? "Show rendered UI" : "Show JSON spec"}
                >
                  {showJson ? <Eye className="size-3.5" /> : <Code className="size-3.5" />}
                </Button>
                <Button
                  variant="ghost"
                  size="icon"
                  className="size-7 rounded-lg text-muted-foreground hover:text-foreground"
                  onClick={() => refresh()}
                  disabled={isLoading}
                  title="Refresh data"
                >
                  <RefreshCw className={`size-3.5 ${isLoading ? "animate-spin" : ""}`} />
                </Button>
              </div>
              {showJson ? (
                <pre className="text-xs font-mono bg-background/50 border border-border/30 rounded-lg p-3 overflow-auto max-h-[500px] text-muted-foreground">
                  {JSON.stringify(activeSpec, null, 2)}
                </pre>
              ) : (
                <DashboardRenderer
                  key={dataVersion}
                  spec={activeSpec}
                  data={data}
                  setData={setData}
                  onDataChange={handleDataChange}
                  loading={isStreaming}
                />
              )}
            </div>
          )}

          {/* Error */}
          {error && !isStreaming && (
            <div className="flex flex-col items-center gap-4 py-16">
              <div className="text-sm text-destructive bg-destructive/10 border border-destructive/20 rounded-xl px-4 py-3">
                {error.message}
              </div>
              <Button
                variant="outline"
                size="sm"
                className="rounded-lg text-xs gap-1.5"
                onClick={generate}
              >
                <RefreshCw className="size-3" />
                Try again
              </Button>
            </div>
          )}
        </div>
      </ScrollArea>
    </div>
  );
}
